In [79]:
import pandas as pd

r_cols = ['userId','movieId','rating']
ratings = pd.read_csv('d:/Study/Data Science course/Data sets/MovieLens/ml-latest-small/ratings.csv', names=r_cols, usecols=range(3))

m_cols = ['movieId','title']
movies = pd.read_csv('d:/Study/Data Science course/Data sets/MovieLens/ml-latest-small/movies.csv', names=m_cols, usecols=range(2))

ratings = pd.merge(movies,ratings)

ratings.head()

   movieId             title  userId  rating
0  movieId             title  userId  rating
1        1  Toy Story (1995)       7     3.0
2        1  Toy Story (1995)       9     4.0
3        1  Toy Story (1995)      13     5.0
4        1  Toy Story (1995)      15     2.0

In [84]:
ratings = ratings.ix[1:]

ratings.head()

  movieId             title userId rating
1       1  Toy Story (1995)      7    3.0
2       1  Toy Story (1995)      9    4.0
3       1  Toy Story (1995)     13    5.0
4       1  Toy Story (1995)     15    2.0
5       1  Toy Story (1995)     19    3.0

In [90]:
userRatings = ratings.pivot_table(index='userId',columns='title',values='rating', aggfunc='last')
userRatings.head()

title,"""Great Performances"" Cats (1998)",$9.99 (2008),'Hellboy': The Seeds of Creation (2004),'Neath the Arizona Skies (1934),'Round Midnight (1986),'Salem's Lot (2004),'Til There Was You (1997),"'burbs, The (1989)",'night Mother (1986),(500) Days of Summer (2009),...,Zulu (1964),Zulu (2013),[REC] (2007),eXistenZ (1999),loudQUIETloud: A Film About the Pixies (2006),xXx (2002),xXx: State of the Union (2005),¡Three Amigos! (1986),À nous la liberté (Freedom for Us) (1931),İtirazım Var (2014)
userId,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [91]:
corrMatrix = userRatings.corr()
corrMatrix.head()

Empty DataFrame
Columns: []
Index: []

In [63]:
corrMatrix = userRatings.corr(method='kendall', min_periods=100)
corrMatrix.head()

Empty DataFrame
Columns: []
Index: []

In [44]:
myRatings = userRatings.iloc[2].dropna()
myRatings

title
Birdcage, The (1996)                          3.0
Black Sheep (1996)                            2.0
Broken Arrow (1996)                           3.0
Down Periscope (1996)                         3.0
Eraser (1996)                                 3.0
Fargo (1996)                                  4.0
Grumpier Old Men (1995)                       4.0
Heat (1995)                                   3.0
Independence Day (a.k.a. ID4) (1996)          3.0
James and the Giant Peach (1996)              3.0
Leaving Las Vegas (1995)                      4.0
Mighty Aphrodite (1995)                       3.0
Mission: Impossible (1996)                    3.0
Mr. Holland's Opus (1995)                     3.0
Phenomenon (1996)                             4.0
Rock, The (1996)                              3.0
Sabrina (1995)                                3.0
Star Trek: First Contact (1996)               4.0
Toy Story (1995)                              4.0
Truth About Cats & Dogs, The (1996)           3.0
Twelve Monkeys (a.k.a. 12 Monkeys) (1995)     5.0
Twister (1996)                                3.0
Wallace & Gromit: A Close Shave (1995)        4.0
White Squall (1996)                           3.0
Willy Wonka & the Chocolate Factory (1971)    5.0
Name: 100, dtype: object

In [45]:
simCandidates = pd.Series()
for i in range(0, len(myRatings.index)):
    print "Adding sims for " + myRatings.index[i] + "..."
    # Retrieve similar movies to this one that I rated
    sims = corrMatrix[myRatings.index[i]].dropna()
    # Now scale its similarity by how well I rated this movie
    sims = sims.map(lambda x: x * myRatings[i])
    # Add the score to the list of similarity candidates
    simCandidates = simCandidates.append(sims)
    
#Glance at our results so far:
print "sorting..."
simCandidates.sort_values(inplace = True, ascending = False)
print simCandidates.head(10)

Adding sims for Birdcage, The (1996)...

KeyError: 'Birdcage, The (1996)'